Review code
anyakkara/sultan-shop pull request #7
Opened 2024-11-07 19:38 UTC by anyakkara

2024-11-07 19:56 UTC, 19begemot98 approved these changes

2024-11-10 09:38 UTC, olya-yevsieienko requested changes
Хорошая работа, молодцы.
Есть несколько моментов:
1. Проверьте, пожалуйста, форматирование, отступы. 
2. Паддинги и маржины не всегда нужно прописывать с помощью четырех или трех значений. https://developer.mozilla.org/ru/docs/Web/CSS/padding
3. Ширина, высота и отступы - числа которые делятся на 4.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/app/page.js
> +import Banner from "@/components/Banner/Banner";
Везде в компоненты добавляем файлик index.js, чтобы сделать импорты более локаничными.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/app/page.module.css
> +}
Лишние пустые строки.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/app/page.module.css
> +.image{
```suggestion
.image {
```

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/app/page.module.css
> +.image{
Проверьте везде, пожалуйста.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/app/page.module.css
> +.product_conteiner{
Максимум одна пустая строка между блоками.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/app/page.module.css
> +    width: 20%;
Тут точно не обойтись без процентов?

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/app/page.module.css
>  }
Во всех файлах одна пустая строка в конце.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.js
> +                <p>
Это точно нельзя просто сверстать, а если на мобильном выглядит как-то иначе, просто доработать стили?

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.js
> +            <div className={styles.banner}>
Это секция.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.js
> +                        <div className={styles.bannerSubheading}>Оптом по Кокчетаву и области</div>
Это параграф.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.js
> +                            <BigYellowButton href="/catalogue">В КАТАЛОГ</BigYellowButton>
Кнопку обсудили на занятии)
И лучше не называть её Yellow. Может случиться так, что где-то кнопка будет такой же, но с других цветом фона.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.css
> +}
Порядок написания css свойств. Проверьте, пожалуйста, вов сех файлах.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.css
> +.Insight {
```suggestion
.insight {
```

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.css
> +    background-color: #FFC85E;
Все цвета в переменные.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.css
> +@media (max-width: 1100px) {
Все брейкпоинты в переменные.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Categories/Categories.js
> +import dishes from '../../app/images/dishes.png';
В одном из файлов прикрепляла структуру папок, проверьте, пожалуйста.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +                        <Link href={"/public"}><Image src={logo2} alt="Logo" height={66}/></Link>
```suggestion
                        <Link href={"/public"}>
                            <Image
                                 src={logo2}
                                 alt="Logo"
                                 height={66}
                             />
                         </Link>
```

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/Header/Header.js
> +                        <Link href={"/public"}><Image src={logo} alt="Logo" height={50}/></Link>
Везде проверить форматирование, чтобы было как предыдущем комментарии.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/ProductList/productList.js
> +      <div className={salestyle.conteinerCard}>
```suggestion
function ProductCard(props) {
    return (
      <div className={salestyle.conteinerCard}>
```

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/ProductList/productList.js
> +    {
Форматирование проверьте везде, пожалуйста.

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/ProductList/productList.module.css
> +    padding: 0px 20px 10px 20px;
```suggestion
    padding: 0px 20px 10px;
```

2024-11-10 09:38 UTC, olya-yevsieienko commented on src/components/ProductList/productList.module.css
> +.product_conteiner{
```suggestion
.product_container {
```

2024-11-21 19:13 UTC, olya-yevsieienko requested changes
Хорошая работа, молодцы)
Нужно поправить несколько моментов.

2024-11-21 19:13 UTC, olya-yevsieienko commented on messages/en.json
> +}
В конце каждого файла должна быть одна пустая строка.
https://dev.to/documendous/why-you-should-end-your-source-files-with-a-new-line-156g

Проверить во всех файлах.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/images/popular.png
Это нужно делать с помощью верстки, а не картинкой)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/layout.js
> +import { languageTag } from "@/paraglide/runtime.js"
Порядок подлкючения импортов .
```suggestion
import Header from "@/components/Header/Header";
import styles from "./globals.scss";
import Footer from "@/components/Footer/Footer";
import { LanguageProvider } from "@inlang/paraglide-next";
import { languageTag } from "@/paraglide/runtime.js";
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/layout.js
> +                <Footer/>
```suggestion
                <Header/>
                <main className={styles.Main}>
                     {children}
                 </main>
                <Footer/>
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/page.jsx
> +            </div>
Если не нужно, лучше удалить)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/page.jsx
> +
Лишняя пустая строка.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/Product.module.scss
> +    }
```suggestion
    justify-content: space-between;
    
    @media (max-width: 950px) {
        flex-direction: column;
    }
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/Product.module.scss
> +}
```suggestion
.card > * {
    width: 50%;
    
    @media (max-width: 950px) {
        width: 100%;
    }
}
```
Везде добавить отступы перед media.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/Product.module.scss
> +.PriceQuantity {
```suggestion
.priceQuantity {
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/Product.module.scss
> +    background: #ffefd1;
Все цвета вынести в переменные.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/Product.module.scss
> +    @media (max-width: 711px) {
И брейкоинты тоже)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/Product.module.scss
> +.PriceList {
```suggestion
.priceList {
```
Лучше везде с маленькой буквы писать.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +import * as m from "@/paraglide/messages.js";
Порядок подключения импортов.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +};
Вынести из этого компонента, возможно, такой функционал пригодится где-то ещё.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +    };
А почему информация статична? Мы ведь должны нажать на товар и увидеть информацию о нём.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +
Давайте разделим это на отдельные компоненты, которые будем покдлючать на страницу.
Так файл будет более читабельным.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +            <BreadCrumbs/>
```suggestion
            <BreadCrumbs />
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +                            </BigYellowButton>
Это просто Button с нужными пропсами.
В какой-то момент она может стать маленькой и зеленой, например)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +                        <div className={styles.ShareButton}><Image src={ShareLogo} alt={'Share logo'}/></div>
```suggestion
                        <div className={styles.ShareButton}>
                            <Image src={ShareLogo} alt={'Share logo'}/>
                        </div>
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/app/product/page.jsx
> +                            elit, dignissim sed nulla ullamcorper enim, malesuada.</p>
```suggestion
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum
                            sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus
                            consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc
                            elit, dignissim sed nulla ullamcorper enim, malesuada.
                        </p>
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Banner/Banner.js
> +}
Тут дублируется код, лучше реализовать это блок иначе.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Banner/Banner.js
> +};
```suggestion
        </>
    );
};
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/BigButton/BigButton.js
> +const BigButton = ({children, onClick, href = "#"}) => {
Пусть будет одна кнопка. А размер будем задавать с помощью пропсов.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/BreadCrumbs/BreadCrumbs.jsx
> +}
Лучше сделать универсальный компонент хлебных крошек, который можно будет подключать и на других страницах.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/BreadCrumbs/BreadCrumbs.module.scss
> +}
Вот такие цепочки .BreadCrumbs > a:last-child:after  лучше не использовать. Будет сложно переопределять стили.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +        <footer className={FooterStyles.footer}>
```suggestion
const Footer = () => {
    return (
        <footer className={FooterStyles.footer}>
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +import EmailField from '@/components/EmailField/EmailField';
Порядок подключения классов.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +                    </p>
```suggestion
                    <p>
                        Компания «Султан» — снабжаем розничные магазины товарами 
                        "под ключ" в Кокчетаве и Акмолинской области
                    </p>
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +                </div>
Это навигация, нужно использовать соответсвующий тег.
И нужно использовать рендер списков)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +                    <Link href="/dishess">Посуда</Link>
И здесь рендер списков)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +            <h2 className={FooterStyles.h2Style}>Скачать прайс-лист:</h2>
Наверное, лучше не использовать здесь h2.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.js
> +                            <Link href="/dishess">Посуда</Link>
Тут происходит дублирование кода. Почему бы не использовать стили вместо дублирования?

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +    color: white;
Везде цвета брать из переменных.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +    z-index: 10;
Почему именно 10, а не 9, например?)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +    margin-right: 95px;
```suggestion
    margin-right: 96px;
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +}
```suggestion
    padding: 20px;
}
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +    background-color: #ffffff;
Все цвета из переменных)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +.connection {
```suggestion
}

.connection {
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +.logo2 {
Лучше не использовать числа в названиях классов)

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Footer/Footer.module.scss
> +        .NavLinksSF a, .ProductsLinksSF a {
Все классы лучше называть с маленькой буквы.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/Header/Header.js
> +import SmallRoundButton from "@/components/SmallRoundButton/SmallRoundButton";
Добавить index.js во все компоненты, чтобы пути выглядели так 
```suggestion
import BigYellowButton from "@/components/BigButton";
import SearchField from "@/components/SearchField";
import SmallRoundButton from "@/components/SmallRoundButton";
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/index.js
> +
```suggestion
export default ProductList from '@/components/ProductList/productList';
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productCard.jsx
> +        <div className={salecard.information}>
```suggestion
        </Link>
        
        <div className={salecard.information}>
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productCard.jsx
> +};
```suggestion
        </div>
      </div>
    );
};
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productCard.module.scss
> +}
```suggestion
    }
}
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productList.jsx
> +  return(
Форматирование.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productList.jsx
> +           .filter((product)=>product.status.includes("popular"))
Лучше отфильтровать это до return, а потом передавать сюда.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productList.jsx
> +           .filter((product)=>product.status.includes("popular"))
То же самое.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productList.jsx
> +
Форматирование.

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productList.module.scss
> +$size_2: 848px;
```suggestion
@import 'src/app/variables.scss';

$size_1: 532px;
$size_2: 848px;
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productList.module.scss
> +    @media (width <= $size_1){
```suggestion
    padding-top: 10px;
}

.product_conteiner{
    @media (width <= $size_1){
```

2024-11-21 19:13 UTC, olya-yevsieienko commented on src/components/ProductList/productList.module.scss
> +        }
```suggestion
        &_m {
            display:none;
        }
        &_l {
            display:none;
        }
```

2024-12-07 16:02 UTC, olya-yevsieienko commented on project.inlang/.gitignore
> +cache
Кажется, это не должно попадать в гит)

2024-12-07 16:02 UTC, olya-yevsieienko commented on project.inlang/project_id
> +c76596601376de25000b91d4f8e13b1bd97e588eb1e0cde3df3452e6023a5230
Кажется, это не должно попадать в гит)

2024-12-07 16:02 UTC, olya-yevsieienko commented on project.inlang/settings.json
> +}
Пустая строка в конце каждого файла.

2024-12-07 16:02 UTC, olya-yevsieienko commented on src/app/catalogue/[id]/page.jsx
> +import { languageTag } from "@/paraglide/runtime"
Порядок подключения импортов.

2024-12-07 16:02 UTC, olya-yevsieienko commented on src/app/catalogue/[id]/page.jsx
> +  const product = products.find((product) => product.id === parseInt(id));
Лучше так
const [product, setProduct] = useState(null);

useEffect(() => {
    setProduct(products.find((product) => product.id === parseInt(id)));
}, [id]);

2024-12-07 16:02 UTC, olya-yevsieienko commented on src/app/variables.scss
> +}
Миксины лучше вынести в отдельный файл.

2024-12-07 16:02 UTC, olya-yevsieienko commented on src/components/Banner/index.js
> +import * as m from '@/paraglide/messages.js';
Порядок покдлючения импортов.

2024-12-07 16:02 UTC, olya-yevsieienko commented on src/components/Footer/index.js
> +import * as m from '@/paraglide/messages';
Порядок подключения импортов.

2024-12-07 16:02 UTC, olya-yevsieienko commented on src/components/Footer/index.js
> +            </div>
Лишняя обертка.

2024-12-07 16:02 UTC, olya-yevsieienko commented on src/components/Footer/index.js
> +                <Link href="/contacts">{m.contacts()}</Link>
Форматирование.

2024-12-07 17:32 UTC, merged